## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
arr = np.random.randint(1, 10, 10)
arr

array([4, 1, 6, 6, 6, 8, 9, 9, 3, 7])

In [3]:
arr1 = np.where((arr > 3) & (arr < 8), -arr, arr)
arr1

array([-4,  1, -6, -6, -6,  8,  9,  9,  3, -7])

**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
arr2 = arr
arr2[arr2 == arr.max()]=0
arr2

array([4, 1, 6, 6, 6, 8, 0, 0, 3, 7])

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [5]:
arr_a = np.random.choice(range(1,10), size=(2,4), replace=False)
arr_a

array([[4, 8, 9, 2],
       [3, 6, 1, 7]])

In [6]:
arr_b = np.random.choice(range(11,20), size=(4,2), replace=False)
arr_b

array([[15, 11],
       [16, 17],
       [18, 19],
       [14, 12]])

In [7]:
combinations = np.array(np.meshgrid(arr_a, arr_b)).T.reshape(-1, 2)
combinations

array([[ 4, 15],
       [ 4, 11],
       [ 4, 16],
       [ 4, 17],
       [ 4, 18],
       [ 4, 19],
       [ 4, 14],
       [ 4, 12],
       [ 8, 15],
       [ 8, 11],
       [ 8, 16],
       [ 8, 17],
       [ 8, 18],
       [ 8, 19],
       [ 8, 14],
       [ 8, 12],
       [ 9, 15],
       [ 9, 11],
       [ 9, 16],
       [ 9, 17],
       [ 9, 18],
       [ 9, 19],
       [ 9, 14],
       [ 9, 12],
       [ 2, 15],
       [ 2, 11],
       [ 2, 16],
       [ 2, 17],
       [ 2, 18],
       [ 2, 19],
       [ 2, 14],
       [ 2, 12],
       [ 3, 15],
       [ 3, 11],
       [ 3, 16],
       [ 3, 17],
       [ 3, 18],
       [ 3, 19],
       [ 3, 14],
       [ 3, 12],
       [ 6, 15],
       [ 6, 11],
       [ 6, 16],
       [ 6, 17],
       [ 6, 18],
       [ 6, 19],
       [ 6, 14],
       [ 6, 12],
       [ 1, 15],
       [ 1, 11],
       [ 1, 16],
       [ 1, 17],
       [ 1, 18],
       [ 1, 19],
       [ 1, 14],
       [ 1, 12],
       [ 7, 15],
       [ 7, 11],
       [ 7, 16

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [44]:
arr_A = np.random.choice(range(1,10), size=(8,3), replace=True)
arr_A

array([[3, 8, 2],
       [6, 7, 3],
       [9, 9, 2],
       [3, 1, 1],
       [7, 6, 1],
       [6, 2, 2],
       [9, 6, 9],
       [6, 5, 7]])

In [45]:
arr_B = np.random.choice(range(1,10), size=(2,2), replace=False)
arr_B

array([[9, 8],
       [5, 4]])

In [51]:
for row_B in arr_B:
    for row_A in arr_A:
        B_in_A = np.isin(row_A, row_B)  # at least one element in row B is in row A
        # print(B_in_A)
        if np.any(B_in_A):
            print(row_A)

[3 8 2]
[9 9 2]
[9 6 9]
[6 5 7]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [87]:
arr_C = np.array([[1, 2, 3],
                  [4, 4, 4],
                  [5, 6, 6],
                  [7, 8, 9],
                  [4, 4, 4],
                  [7, 7, 7],
                  [7, 8, 9],
                  [4, 4, 4],
                  [1, 2, 3]])

In [88]:
for row in arr_C:
    if len(np.unique(row))>1:
        print(row)

[1 2 3]
[5 6 6]
[7 8 9]
[7 8 9]
[1 2 3]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [89]:
arr_D = np.array([[1, 2, 3],
                  [4, 4, 4],
                  [5, 6, 6],
                  [7, 8, 9],
                  [4, 4, 4],
                  [1, 2, 3]])

In [93]:
print(np.unique(arr_D, axis=0))

#v2 - completely deletes duplicate rows (with initial)
_, inverse_indices = np.unique(arr_D, axis=0, return_inverse=True)
different_rows = arr_D[np.where(np.bincount(inverse_indices) == 1)]
print(different_rows)

[[1 2 3]
 [4 4 4]
 [5 6 6]
 [7 8 9]]
[[5 6 6]
 [7 8 9]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [108]:
# v1 list
arr_lst = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
multiplication = 1
counter = 0
for row in arr_lst:
    if counter == len(row):
        break
    elif row[counter] != 0:
        multiplication *= row[counter]
    counter += 1
print(multiplication)

# v2 numpy
arr = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
diagonal_elements = np.diag(arr)
# print(diagonal_elements)
non_zero_diagonal = diagonal_elements[diagonal_elements != 0]
# print(non_zero_diagonal)
multiplication_of_diagonal = np.prod(non_zero_diagonal)
print(multiplication_of_diagonal)


3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [115]:
# v1 list
a = [1, 2, 2, 4]
b = [4, 2, 1, 2]
print(a==b)
print(sorted(a) == sorted(b))

# v2 numpy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
equal = np.array_equal(np.sort(x), np.sort(y)) # np.array_equiv() - compare regardless of arrrays shape
print(equal)

False
True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [138]:
# v1 list
a = [6, 2, 0, 3, 0, 0, 5, 7, 0]
b = []
for counter in range(len(a)-1):
    if a[counter] == 0:
        b.append(a[counter+1])
print(max(b))

# v2 numpy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero_idx = np.where(x == 0)[0]      # position of zeros
# print(zero_idx)
valid_idx = zero_idx[(zero_idx+1) < len(x)]     # valid index of zeros
# print(valid_idx)
max_element = np.max(x[valid_idx+1])    # elements that are followed by a zero
print(max_element)

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [9]:
# v1 list
unique_elements = list(set(a))
counts = [a.count(element) for element in unique_elements]
print(unique_elements, counts)

from collections import Counter
a = [2, 2, 2, 3, 3, 3, 5]
print(Counter(a))

# v2 numpy
x = np.array([2, 2, 2, 3, 3, 3, 5])
unique_values, counts = np.unique(x, return_counts=True)
print(unique_values, counts)

[2, 3, 5] [3, 3, 1]
Counter({2: 3, 3: 3, 5: 1})
[2 3 5] [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [29]:
# Euclid distance between 2 coordinates = sqrt((x1 - y1)^2 + (x2 - y2)^2 + ... + (xd - yd)^2)
matrix1 = np.array([[1, 2],
                    [3, 4]])
matrix2 = np.array([[5, 6],
                    [7, 8]])
diff = matrix1[:, np.newaxis] - matrix2
squared_diff = diff ** 2
sum_squared_diff = np.sum(squared_diff, axis=2)
distance_matrix = np.sqrt(sum_squared_diff)
print(distance_matrix)

from scipy.spatial.distance import cdist
distance_matrix = cdist(matrix1, matrix2, metric='euclidean')
print(distance_matrix)

[[5.65685425 8.48528137]
 [2.82842712 5.65685425]]
[[5.65685425 8.48528137]
 [2.82842712 5.65685425]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [30]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [4]:
calorie_stats = np.loadtxt("./input_data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [35]:
CrunchieMunchies_calories = 60
average_calories = np.mean(calorie_stats) - CrunchieMunchies_calories
average_calories

46.883116883116884

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [36]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [39]:
median_calories = np.median(calorie_stats)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [5]:
percentile = np.percentile(calorie_stats, q=[0, 1, 2, 3, 4, 5, 10, 25, 50, 75, 100])
print(percentile)
nth_percentile = np.percentile(calorie_stats, q=4)
print(nth_percentile)
# 4th_percentile means that approx. 4% (or 3.28% exactly) of all cereals has <= 60 calories (i.e. CrunchieMunches)

[ 50.   50.   50.   55.6  70.   70.   90.  100.  110.  110.  160. ]
70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [69]:
more_calories = np.mean(calorie_stats > 60)
print(more_calories*100)
# 96% of all cereals is > 60 calories

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [70]:
# std = sqrt( sum((x_i - x_mean)**2 / (n-1) )
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [89]:
# more_calories => более 96% всех калорий у остальных производителей > 60 Ккал
# calorie_std => расброс данных небольшой около 20% - следовательно данные равномерно распределенные